dist: bionic    # используем Ubuntu Bionic

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
    # список переменных окружения, влияющих на матрицу сборки:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

branches:
  only:
    - master

addons:
  apt:
    packages:
      - lcov

script: # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCHECK_TEST_COVERAGE=1
    - cmake --build .
    - ctest --output-on-failure

after_success:
  # Create lcov report
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
