dist: bionic    # используем Ubuntu Bionic

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
    # список переменных окружения, влияющих на матрицу сборки:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

branches:
  only:
    - master

addons:
  apt:
    packages:
      - lcov

script: # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
    - ctest --output-on-failure

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
