dist: trusty    # используем Ubuntu 14.04 Trusty
sudo: required  # используем Virtual Machine (а не Docker container)

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
    # список переменных окружения, влияющих на матрицу сборки:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

branches:
  only:
    - master
    - develop

install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
    - ctest --output-on-failure